# Generated by Django 5.1.3 on 2025-04-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bestandsverzeichnis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grundbuch_von",
                    models.CharField(help_text="z.B. Roisdorf", max_length=100),
                ),
                (
                    "grundbuchblatt_nummer",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "laufende_grundstuecksnummer",
                    models.CharField(
                        help_text="Lfd. Nr. im Bestandsverzeichnis, z.B. '1'",
                        max_length=10,
                    ),
                ),
                ("bezirk", models.CharField(blank=True, max_length=100, null=True)),
                ("flur", models.CharField(blank=True, max_length=100, null=True)),
                ("flurstueck", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "wirtschaftsart",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AbteilungIIIEintrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grundbuch_von",
                    models.CharField(help_text="z.B. Roisdorf", max_length=100),
                ),
                (
                    "grundbuchblatt_nummer",
                    models.CharField(help_text="z.B. 3351", max_length=20),
                ),
                (
                    "laufende_grundstuecksnummer",
                    models.CharField(
                        help_text="Bezug zum Bestandsverzeichnis (z.\u202fB. '1')",
                        max_length=10,
                    ),
                ),
                (
                    "pfandart",
                    models.CharField(
                        help_text="z.B. Grundschuld, Hypothek", max_length=100
                    ),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2, help_text="z.B. 150000.00", max_digits=12
                    ),
                ),
                (
                    "glaeubiger",
                    models.CharField(
                        blank=True,
                        help_text="z.B. Sparkasse Köln-Bonn",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("eintragungsdatum", models.DateField(blank=True, null=True)),
                (
                    "bestandsverzeichnis",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optionaler Bezug zum Grundstück",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.bestandsverzeichnis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbteilungIIEintrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grundbuch_von",
                    models.CharField(
                        help_text="Name des Grundbuchbezirks, z.B. Roisdorf",
                        max_length=100,
                    ),
                ),
                (
                    "grundbuchblatt_nummer",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "laufende_eintragsnummer",
                    models.CharField(
                        help_text="z.\u202fB. '1' oder '2'", max_length=10
                    ),
                ),
                (
                    "laufende_grundstuecksnummer",
                    models.CharField(
                        blank=True,
                        help_text="Bezug zum Bestandsverzeichnis (z.B. '1')",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "lastentext",
                    models.TextField(
                        help_text="Der erkannte Text der Last oder Beschränkung"
                    ),
                ),
                (
                    "bestandsverzeichnis",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optionaler direkter Bezug zum Grundstück, wenn bereits vorhanden",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.bestandsverzeichnis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbteilungIEintrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grundbuch_von",
                    models.CharField(help_text="z.\u202fB. Roisdorf", max_length=100),
                ),
                (
                    "grundbuchblatt_nummer",
                    models.CharField(
                        help_text="Blattnummer, z.\u202fB. 3351", max_length=20
                    ),
                ),
                (
                    "laufende_grundstuecksnummer",
                    models.CharField(
                        help_text="Bezug zum Bestandsverzeichnis (z.\u202fB. '1')",
                        max_length=10,
                    ),
                ),
                (
                    "eigentuemer_name",
                    models.CharField(
                        help_text="z.\u202fB. Max Mustermann", max_length=255
                    ),
                ),
                ("geburtsdatum", models.DateField(blank=True, null=True)),
                ("wohnort", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "erwerbsgrund",
                    models.CharField(
                        blank=True,
                        help_text="z.\u202fB. Kaufvertrag vom 01.01.2023",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "bestandsverzeichnis",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optionaler Bezug zum Grundstück",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.bestandsverzeichnis",
                    ),
                ),
            ],
        ),
    ]
